name: Java CI for Lab 3

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and Run Tests
        run: |
          
          mkdir -p bin
          
          
          javac -d bin -cp "lib/*:." LAB_3/src/*.java LAB_3/test/*.java
          
          
          java -cp "bin:lib/*" org.junit.platform.console.ConsoleLauncher --scan-class-path --reports-dir=test-reports